nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Sélection de téléphones mobiles haut de gamme
            version: "0.1"
        components:
            securitySchemes:
                bearerAuth:    
                    name: Authorization        # arbitrary name for the security scheme
                    type: apiKey
                    in: header
                    scheme: bearer
                    bearerFormat: JWT    # optional, arbitrary value for documentation purposes
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            # example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk5NTIxMDIsImV4cCI6MTY5OTk1MjcwMiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFydGh1ci5waW50b0BleGFtcGxlLm5ldCJ9.Iz6lFDUQoeyZLxCNiCUPxwC_Qr3wTJ_XCpscposZ93yU0LiXO-MZNz5kzuVGJXC55BlHrhy3CMQGHLwrRMxulNVusWF25TKMMKCDAAU6jXGRqXGaVAjqaLv5EPVz4YOrwNvEYMaPybqK3JNGOYsK2D_oBXH7_G-VwIJ0N4ldoQHOn37ApKnH3sdzILmb3qsgZeq5KaDY4vJRmTp4t7F_AuwzNlw_VLwQQk26wjMK4Ev4EnVsmtqeFfkB2fSXsJ8HjuDuYh5BUMW1B_DL2lcbu75aNr_KLwCxjGQ7eELFoKAiCtCUOJakYJu_JxAKsf1qrzmeJmLvjbtQIPLV5HiiJQ
                # Request_body:
                    # type: object
                    # properties:
                    #     firstname:
                    #         type: string
                    #         example: firstname
                    #     lastname: 
                    #         type: string
                    #         example: lastname
                    #     email:
                    #         type: string
                    #         example: user@email.com
        paths:
            /api/check_cred:
                post:
                    tags:
                        - LogIn
                    summary: Identification de l'utilisateur via JWT
                    requestBody:
                        description: Connexion avec __email__ et __mot de passe__ pour obtenir un jeton d'authentification
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                            default: client@email.com
                                        password:
                                            type: string
                                            default: 123456
                                    example:
                                        username: foo@bar.com
                                        password: "123456"
                    responses:
                        '200':
                            description: Obtention du **jeton d'authentification**
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '401':
                            description: Mauvais identifiant ou mot de passe
            /api/users:
                post:
                    requestBody:
                        required: true
                        description: Les informations de l'utilisateur que l'on souhaite crééer
                        content:
                            application/json:
                                schema:
                                    # 
                                    type: object
                                    properties:
                                        firstname:
                                            type: string
                                            example: firstname
                                        lastname: 
                                            type: string
                                            example: lastname
                                        email:
                                            type: string
                                            example: user@email.com
            /api/users/{id}:
                get:
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                            type: integer
                delete:
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                            type: integer
            /api/products/{id}:
                get:
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                            type: integer
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

